name: python testing
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
 
      - name: Create directory for Python tool cache
        run: sudo mkdir -p /Users/runner/hostedtoolcache
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
         
      - name: Use python
        run: |
          python --version
